all:
  children:
    controllers:
      hosts:
        cp1:
          ansible_host: controller.voice.vivolution.ae
          ansible_port: 22
          ansible_user: cpadmin
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /Users/jay/.ssh/vivolution-sbc-cp1-ed25519
          ansible_ssh_common_args: >-
            -F /dev/null
            -o IdentitiesOnly=yes
            -o StrictHostKeyChecking=yes
            -o 'UserKnownHostsFile="{{ inventory_dir }}/generated/known_hosts"'
            -o GlobalKnownHostsFile=/dev/null
