---
- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: restarted
  when: cp_systemd_resolved_active | default(false) | bool

- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted
