---
voice_fixture_root: /opt/vivolution/voice-fixture
voice_fixture_config_root: /etc/vivolution/voice-fixture
voice_fixture_state_root: /var/lib/vivolution/voice-fixture
voice_fixture_results_root: /var/lib/vivolution/voice-fixture/results
voice_fixture_runtime_root: /run/vivolution-voice-fixture
voice_fixture_pki_root: /etc/vivolution/voice-fixture/pki-current
voice_fixture_pki_generations_root: /etc/vivolution/voice-fixture/pki-generations
voice_fixture_pki_staging_root: /etc/vivolution/voice-fixture/pki-staging
voice_fixture_pki_extensions_root: /etc/vivolution/voice-fixture/pki-extensions
voice_fixture_asterisk_image_tag: localhost/vivolution/voice-fixture-asterisk:22.10.1-xmldoc1-nosounds1-tlsbind4-dns1
voice_fixture_sipp_image_tag: localhost/vivolution/voice-fixture-sipp:3.7.7-sni1-txn1

voice_fixture_remove_images: false
voice_fixture_remove_results: false
voice_fixture_remove_pki: false
voice_fixture_remove_results_acknowledgement: ''
voice_fixture_remove_pki_acknowledgement: ''
