"""Bounded security core for the Vivolution Edge Agent."""

from .security_core import (
    AbortResult,
    AgentError,
    CommitResult,
    DependencyUnavailable,
    EnvelopeRejected,
    LocalContext,
    PinnedKeyring,
    SchemaValidationUnavailable,
    SignatureVerificationError,
    StageResult,
    StateCorruptionError,
    StateLifecycleError,
    StateSecurityError,
    StateStore,
    StateVersionError,
    abort_pending,
    commit_pending_after_health,
    inspect_protected_state,
    validate_structural_envelope,
    verify_and_stage,
)

__all__ = [
    "AbortResult",
    "AgentError",
    "CommitResult",
    "DependencyUnavailable",
    "EnvelopeRejected",
    "LocalContext",
    "PinnedKeyring",
    "SchemaValidationUnavailable",
    "SignatureVerificationError",
    "StageResult",
    "StateCorruptionError",
    "StateLifecycleError",
    "StateSecurityError",
    "StateStore",
    "StateVersionError",
    "abort_pending",
    "commit_pending_after_health",
    "inspect_protected_state",
    "validate_structural_envelope",
    "verify_and_stage",
]
